# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170621_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='Garfield', max_length=30, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
