# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.CharField(default='owned', max_length=15, verbose_name='Dueño'),
            preserve_default=False,
        ),
    ]
