# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_pet_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
