# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('owner', models.CharField(max_length=15, verbose_name='Dueño')),
                ('credits', models.IntegerField(default=0, verbose_name='Créditos')),
                ('status', models.IntegerField(default=0, verbose_name='Estado')),
                ('happiness', models.IntegerField(default=0, verbose_name='Felicidaad')),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
