# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0003_auto_20170621_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('species', models.CharField(max_length=30, verbose_name='especie')),
                ('owner', models.CharField(max_length=15, verbose_name='dueño')),
                ('credits', models.IntegerField(default=0, verbose_name='créditos')),
                ('status', models.IntegerField(default=0, verbose_name='estado')),
                ('happiness', models.IntegerField(default=0, verbose_name='felicidaad')),
            ],
        ),
    ]
