# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0005_auto_20170621_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='happiness',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='species',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='bla bla', max_length=255, verbose_name='descripción'),
            preserve_default=False,
        ),
    ]
