# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 05:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0008_auto_20170621_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 5, 48, 3, 881466, tzinfo=utc), verbose_name='plazo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pet_bot.Pet', verbose_name='Mascota'),
        ),
    ]
