# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-22 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0010_auto_20170622_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='happiness',
        ),
        migrations.AddField(
            model_name='pet',
            name='available_credits',
            field=models.IntegerField(default=0, verbose_name='créditosdisponibles'),
        ),
        migrations.AddField(
            model_name='pet',
            name='required_credits',
            field=models.IntegerField(default=0, verbose_name='créditosnecesitados'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='state',
            field=models.IntegerField(choices=[(0, 'Ok'), (1, 'Aburrido'), (2, 'Hambriento'), (3, 'Con frío'), (4, 'Sucio'), (5, 'Enfermo'), (6, 'Herido'), (7, 'Triste')], default=0, verbose_name='estado'),
        ),
    ]
