# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-22 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0011_auto_20170622_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='available_credits',
            field=models.IntegerField(default=0, verbose_name='créditos disponibles'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='required_credits',
            field=models.IntegerField(default=0, verbose_name='créditos necesitados'),
        ),
    ]
