# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0013_auto_20170623_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner_id',
            field=models.BigIntegerField(default=0, verbose_name='dueño_id'),
            preserve_default=False,
        ),
    ]
