# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0014_pet_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner_id',
            new_name='id_owner',
        ),
    ]
