# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_bot', '0015_auto_20170623_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='id_owner',
            new_name='owner_id',
        ),
    ]
